### PR TITLE
Master

### PR DESCRIPTION
**Pull request by Jourdodadams**

### CODE REVIEW

**Comment by nickfox** [comment]
Hi, I'm not totally sure what you are doing here. You are working on version 2.0.0? GpsTracker is up to version 4.0.3. Please let me know.

Nick

**Comment by Jourdodadams** [comment]
Hi Nick,

Thanks for contacting me. I am definitely an amateur at this type of stuff.
I have been trying to figure this out for the past week and a bit lol. I
have gotten the DisplayMaps.aspx page to load but no map shows up it is
just blank. Do think you could tell me what I am doing wrong?

Jourdan,
Thanks

**Comment by Jourdodadams** [comment]
Also, I should let you know. I am using mssql server and asp.net. The first
option you provided.

**Comment by nickfox** [comment]
can you please give me the url of your display map page.

n

**Pull request closed without merging**
